# Generated by Django 6.0.2 on 2026-02-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_account_links'),
        ('planner', '0003_vote_details'),
    ]

    operations = [
    ]
